<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemMaintenanceInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('item_maintenance_infos')->insert([
            [
                'itemID' => 1,
                'itemName' => 'Ankle Weights',
                'quantity' => 100,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => '2KG ankle weights for resistance training',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 2,
                'itemName' => 'Foam Roller',
                'quantity' => 200,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Massage foam roller for muscle recovery and myofascial release',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 3,
                'itemName' => 'Hot/Cold Pack',
                'quantity' => 100,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Item',
                'description' => 'Reusable hot and cold therapy packs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 4,
                'itemName' => 'Resistance Band Heavy',
                'quantity' => 200,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Heavy resistance band for advanced strength training',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 5,
                'itemName' => 'Resistance Band Light',
                'quantity' => 120,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Light resistance band for rehabilitation exercises',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 6,
                'itemName' => 'Resistance Band Medium',
                'quantity' => 150,
                'stockLevel' => '20',
                'condition' => 'Fair',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Medium resistance band for general strength training',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 7,
                'itemName' => 'Swiss Ball',
                'quantity' => 100,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Exercise ball for balance and core strengthening',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 8,
                'itemName' => 'TENS Machine',
                'quantity' => 150,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Transcutaneous electrical nerve stimulation device for pain management',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 9,
                'itemName' => 'Treadmill',
                'quantity' => 150,
                'stockLevel' => '20',
                'condition' => 'Needs repair',
                'status' => 'Under maintenance',
                'category' => 'Equipment',
                'description' => 'Commercial treadmill for cardio and gait training - currently being serviced',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 10,
                'itemName' => 'Walking Frame',
                'quantity' => 100,
                'stockLevel' => '10',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Adjustable walking frame for mobility assistance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 11,
                'itemName' => 'Therapy Tape (Kinesiology)',
                'quantity' => 250,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Item',
                'description' => 'Elastic kinesiology tape for muscle support and pain relief',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 12,
                'itemName' => 'Disposable Electrode Pads',
                'quantity' => 152,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Item',
                'description' => 'Self-adhesive electrode pads for TENS/EMS machines',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 13,
                'itemName' => 'Paraffin Wax Bath',
                'quantity' => 80,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Item',
                'description' => 'Paraffin wax therapy bath for pain relief and joint mobility',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 14,
                'itemName' => 'Therapy Putty',
                'quantity' => 100,
                'stockLevel' => '20',
                'condition' => 'Good',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Hand therapy putty for grip strength and finger rehabilitation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemID' => 15,
                'itemName' => 'Ultrasound Gel',
                'quantity' => 19,
                'stockLevel' => '20',
                'condition' => 'Excellent',
                'status' => 'Available',
                'category' => 'Equipment',
                'description' => 'Conductive gel for ultrasound therapy machines',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}