@extends('layouts.app')

@section('title', 'Report Details - #' . $report->reportID)

@section('content')
<style>
@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap");

.report-container {
    max-width: 900px;
    margin: 0 auto;
    padding: 40px 20px;
    font-family: 'Inter', sans-serif;
}

.report-header {
    background: white;
    border-radius: 18px;
    padding: 30px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
    margin-bottom: 30px;
    display: flex;
    justify-content: space-between;
    align-items: start;
    flex-wrap: wrap;
    gap: 20px;
}

.report-title {
    font-size: 28px;
    font-weight: 700;
    color: #1f2937;
    margin: 0 0 20px 0;
}

.report-details {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
}

.detail-item {
    display: flex;
    flex-direction: column;
}

.detail-label {
    font-size: 12px;
    text-transform: uppercase;
    color: #6b7280;
    letter-spacing: 0.6px;
    margin-bottom: 5px;
    font-weight: 600;
}

.detail-value {
    font-size: 16px;
    color: #111827;
    font-weight: 500;
}

.badge {
    padding: 8px 16px;
    border-radius: 999px;
    font-size: 13px;
    font-weight: 600;
    display: inline-block;
    width: fit-content;
}

/* ================= BUTTONS ================= */
.btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 22px;
    font-weight: 600;
    border-radius: 12px;
    cursor: pointer;
    border: none;
    transition: all 0.3s ease;
    text-decoration: none;
    font-size: 14px;
}

.btn-secondary {
    background-color: #f0f0f0;
    color: #333;
}

.btn-primary {
    background-color: #3b82f6;
    color: white;
}

.btn-primary:hover {
    background-color: #2563eb;
    box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);
}

.badge-usage {
    background: #dbeafe;
    color: #0369a1;
}

.badge-maintenance {
    background: #fecaca;
    color: #dc2626;
}

.action-buttons-group {
    display: flex;
    gap: 12px;
    margin-top: 20px;
}


.report-content {
    background: white;
    border-radius: 18px;
    padding: 30px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
    min-height: 400px;
}

.empty-state {
    text-align: center;
    color: #6b7280;
    padding: 60px 20px;
}

.empty-state-icon {
    font-size: 48px;
    margin-bottom: 15px;
}
.report-container {
    width: 100%;
    max-width: 1200px; /* Increased for wider tables */
    margin: 0 auto;
    padding: 20px;
    box-sizing: border-box;
    font-family: 'Inter', sans-serif;
}

/* Responsive Table Wrapper */
.report-content {
    background: white;
    border-radius: 18px;
    padding: clamp(15px, 3vw, 30px); /* Responsive padding */
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
    min-height: 400px;
    overflow-x: auto; /* Enables horizontal scroll on small screens */
    -webkit-overflow-scrolling: touch;
}

.report-table {
    width: 100%;
    border-collapse: collapse;
    min-width: 600px; /* Prevents squishing */
}

.report-table th {
    background: #f9fafb;
    border-bottom: 2px solid #e5e7eb;
    padding: 16px 14px;
    text-align: left;
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
    color: #6b7280;
    white-space: nowrap;
}

.report-table td {
    padding: 16px 14px;
    color: #374151;
    border-bottom: 1px solid #f1f5f9;
    font-size: 14px;
}

/* Helper class for JS to hide columns */
.column-hidden {
    display: none !important;
}
</style>

<div class="report-container">
    <div class="report-header">
        <div style="flex: 1;">
            <h1 class="report-title">Report #{{ $report->reportID }}</h1>
            <div class="report-details">
                <div class="detail-item">
                    <span class="detail-label">Report Type</span>
                    <span class="badge badge-{{ strtolower($report->reportType) }}" style="margin-left: 2px;">
                        {{ ucfirst($report->reportType) }}
                    </span>
                </div>
                <div class="detail-item">
                    <span class="detail-label">Generated By</span>
                    <span class="detail-value">{{ $report->user->name ?? 'N/A' }}</span>
                </div>
                <div class="detail-item">
                    <span class="detail-label">Generated Date</span>
                    <span class="detail-value">{{ $report->generatedAt->format('Y-m-d') }}</span>
                </div>
            </div>
        </div>

        <div class="btn-holder">
                <a href="{{ route('admin.reports.dashboard') }}" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Back
                </a>
                <button type="submit" class="btn btn-primary" onclick="printReport()">
                    <i class="fas fa-print"></i> Print Report
                </button>
            </div>

        <!-- <div class="action-buttons-group" style="flex-direction: column; margin-top: 0;">
            <button type="button" class="btn btn-primary" onclick="printReport()">
                <i class="fas fa-download"></i> Export / Print
            </button>
            <a href="{{ route('admin.reports.dashboard') }}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Back 
            </a>
        </div>
    </div> -->
<!--  -->
    <div class="report-content">
            @if(strtolower($report->reportType) === 'usage')
                <table class="report-table" id="usageTable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Usage ID</th>
                            <th>Item ID</th>
                            <th>Item Name</th>
                            <th>Quantity</th>
                            <th>Used By</th>
                            <th>Used Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reportData as $record)
                            @foreach($record->itemUsages as $index => $usage)
                                <tr>
                                    <td>{{ $loop->parent->iteration }}</td>
                                    <td>{{ $record->usageID }}</td>
                                    <td>{{ $usage->item->itemID ?? 'N/A' }}</td>
                                    <td>{{ $usage->item->product_name ?? 'N/A' }}</td>
                                    <td>{{ $usage->quantity ?? 'N/A' }}</td>
                                    <td>{{ $record->user->name ?? 'N/A' }}</td>
                                    <td>{{ $record->usageDate?->format('Y-m-d H:i') ?? 'N/A' }}</td>
                                </tr>
                            @endforeach
                        @empty
                            <tr>
                                <td colspan="7" style="padding: 50px 20px; text-align: center; color: #6b7280;">
                                    <div style="font-size: 48px; margin-bottom: 10px;">📋</div>
                                    No usage data found for this report period.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>

            @elseif(strtolower($report->reportType) === 'maintenance')
                <table class="report-table" id="maintenanceTable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Request ID</th>
                            <th>Item ID</th>
                            <th>Equipment Name</th>
                            <th>Item Issue</th>
                            <th>Submitted By</th>
                            <th>Status</th>
                            <th>Date Submitted</th>
                            <th>Details Maintenance</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reportData as $request)
                            @forelse($request->itemMaintenances as $index => $maintenance)
                                <tr>
                                    <td>{{ $loop->parent->iteration }}</td>
                                    <td>{{ $request->requestID }}</td>
                                    <td>{{ $maintenance->itemInfo->itemID ?? 'N/A' }}</td>
                                    <td>{{ $maintenance->itemInfo->product_name ?? 'N/A' }}</td>
                                    <td>{{ $maintenance->itemIssue ?? 'N/A' }}</td>
                                    <td>{{ $request->submitter->name ?? 'N/A' }}</td>
                                    <td>
                                        <span>
                                            {{ ucfirst($request->status) }}
                                        </span>
                                    </td>
                                    <td>{{ $request->dateSubmitted?->format('Y-m-d H:i') ?? 'N/A' }}</td>
                                    <td style="max-width: 250px; word-break: break-word;">{{ $maintenance->detailsMaintenance ?? 'N/A' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td>{{ $loop->parent->iteration }}</td>
                                    <td colspan="8" style="color: #6b7280; font-style: italic;">No maintenance items for this request</td>
                                </tr>
                            @endforelse
                        @empty
                            <tr>
                                <td colspan="9" style="padding: 50px 20px; text-align: center; color: #6b7280;">
                                    <div style="font-size: 48px; margin-bottom: 10px;">📋</div>
                                    No maintenance data found for this report period.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            @else
                <div class="empty-state">
                    <div class="empty-state-icon">❓</div>
                    <h3>Unknown Report Type</h3>
                    <p>This report type is not recognized.</p>
                </div>
            @endif
        </div>
</div>

<!-- Printable template (hidden) -->
<div id="printableArea" style="display:none;">
@include('admin.GenerateReport.printable_template_fragment')
</div>

<script>
function printReport() {
    const printable = document.getElementById('printableArea').innerHTML;
    const styles = `
        <style>
            @page { size: A4; margin: 20mm; }
            body { font-family: 'Inter', Arial, sans-serif; color: #111; }
            table { border-collapse: collapse; width: 100%; }
            th { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; font-weight:700; }
            td { padding: 8px; vertical-align: top; }
        </style>
    `;

    const html = '<!doctype html><html><head><meta charset="utf-8"><title>Report #{{ $report->reportID }}</title>' + styles + '</head><body>' + printable + '</body></html>';

    // Open new window
    const w = window.open('', '_blank', 'width=900,height=700');
    if (!w) {
        alert('Please allow popups for this site to print reports.');
        return;
    }

    // Write content to new window
    w.document.open();
    w.document.write(html);
    w.document.close();
    w.focus();

    // Wait for content to load, then print
    setTimeout(() => {
        try { w.print(); } catch (e) { console.error('Print error:', e); }
    }, 300);
}
// Auto-trigger print when ?print=1 is present
document.addEventListener('DOMContentLoaded', function() {
    try {
        const params = new URLSearchParams(window.location.search);
        if (params.get('print') === '1') {
            // give the page a moment to render
            setTimeout(() => { if (typeof printReport === 'function') printReport(); }, 500);
        }
    } catch (e) { /* ignore */ }
});

/**
 * Scans a table and hides any column where EVERY row contains "N/A"
 */
function hideEmptyColumns() {
    const tables = document.querySelectorAll('.report-table');
    
    tables.forEach(table => {
        const rows = table.querySelectorAll('tbody tr');
        if (rows.length === 0 || (rows.length === 1 && rows[0].cells.length === 1)) return;

        const colCount = table.querySelectorAll('thead th').length;

        for (let i = 0; i < colCount; i++) {
            let allNA = true;
            let hasData = false;

            rows.forEach(row => {
                const cell = row.cells[i];
                if (cell) {
                    hasData = true;
                    const text = cell.textContent.trim();
                    // If even one row has something other than N/A, we show the column
                    if (text !== 'N/A' && text !== '') {
                        allNA = false;
                    }
                }
            });

            if (allNA && hasData) {
                // Hide header
                table.querySelectorAll('thead th')[i].classList.add('column-hidden');
                // Hide all cells in this column
                rows.forEach(row => {
                    if (row.cells[i]) row.cells[i].classList.add('column-hidden');
                });
            }
        }
    });
}

document.addEventListener('DOMContentLoaded', hideEmptyColumns);
</script>
@endsection
