@extends('layouts.app')

@section('title', 'Report Details - #' . $report->reportID)

@section('content')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<style>
@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap");

.report-container {
    max-width: 900px;
    margin: 0 auto;
    padding: 40px 20px;
    font-family: 'Inter', sans-serif;
}

.report-header {
    background: white;
    border-radius: 18px;
    padding: 30px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
    margin-bottom: 30px;
    display: flex;
    justify-content: space-between;
    align-items: start;
    flex-wrap: wrap;
    gap: 20px;
}

.report-title {
    font-size: 28px;
    font-weight: 700;
    color: #1f2937;
    margin: 0 0 20px 0;
}

.report-details {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
}

.detail-item {
    display: flex;
    flex-direction: column;
}

.detail-label {
    font-size: 12px;
    text-transform: uppercase;
    color: #6b7280;
    letter-spacing: 0.6px;
    margin-bottom: 5px;
    font-weight: 600;
}

.detail-value {
    font-size: 16px;
    color: #111827;
    font-weight: 500;
}

.badge {
    padding: 8px 16px;
    border-radius: 999px;
    font-size: 13px;
    font-weight: 600;
    display: inline-block;
    width: fit-content;
}

/* ================= BUTTONS ================= */
.btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 22px;
    font-weight: 600;
    border-radius: 12px;
    cursor: pointer;
    border: none;
    transition: all 0.3s ease;
    text-decoration: none;
    font-size: 14px;
}

.btn-secondary {
    background-color: #f0f0f0;
    color: #333;
}

.btn-primary {
    background-color: #3b82f6;
    color: white;
}

.btn-primary:hover {
    background-color: #2563eb;
    box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);
}

.badge-usage { background: #dbeafe; color: #0369a1; }
.badge-maintenance { background: #fecaca; color: #dc2626; }

.action-buttons-group {
    display: flex;
    gap: 12px;
    margin-top: 20px;
}

.report-content {
    background: white;
    border-radius: 18px;
    padding: 30px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
    min-height: 400px;
}

.empty-state {
    text-align: center;
    color: #6b7280;
    padding: 60px 20px;
}

.empty-state-icon {
    font-size: 48px;
    margin-bottom: 15px;
}

/* ================= CHART CONTAINER ================= */
.chart-wrapper {
    background: #f9fafb;
    border-radius: 12px;
    padding: 20px;
    margin-bottom: 30px;
    border: 1px solid #e5e7eb;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 350px;
}
</style>

<div class="report-container">
    <div class="report-header">
        <div style="flex: 1;">
            <h1 class="report-title">Report #{{ $report->reportID }}</h1>
            <div class="report-details">
                <div class="detail-item">
                    <span class="detail-label">Report Type</span>
                    <span class="badge badge-{{ strtolower($report->reportType) }}" style="margin-left: 2px;">
                        {{ ucfirst($report->reportType) }}
                    </span>
                </div>
                <div class="detail-item">
                    <span class="detail-label">Generated By</span>
                    <span class="detail-value">{{ $report->user->name ?? 'N/A' }}</span>
                </div>
                <div class="detail-item">
                    <span class="detail-label">Generated Date</span>
                    <span class="detail-value">{{ $report->generatedAt->format('Y-m-d') }}</span>
                </div>
            </div>
        </div>

        <div class="btn-holder">
            <a href="{{ route('admin.reports.dashboard') }}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Back
            </a>
            <button type="submit" class="btn btn-primary" onclick="printReport()">
                <i class="fas fa-print"></i> Print Report
            </button>
        </div>
    </div>

    <div class="report-content">

        {{-- ================= DATA PREPARATION FOR CHART ================= --}}
        @php
            $chartLabels = [];
            $chartValues = [];
            $chartTitle = '';

            if (strtolower($report->reportType) === 'usage') {
                $chartTitle = 'Most Used Equipment (By Quantity)';
                $itemCounts = [];
                
                foreach($reportData as $record) {
                    foreach($record->itemUsages as $usage) {
                        $name = $usage->itemMaintenanceInfo->itemName ?? 'Unknown Item';
                        $qty = is_numeric($usage->quantityUsed) ? (int)$usage->quantityUsed : 1;
                        
                        if(!isset($itemCounts[$name])) {
                            $itemCounts[$name] = 0;
                        }
                        $itemCounts[$name] += $qty;
                    }
                }
                arsort($itemCounts); // Sort highest to lowest
                $chartLabels = array_keys($itemCounts);
                $chartValues = array_values($itemCounts);
                
            } elseif (strtolower($report->reportType) === 'maintenance') {
                $chartTitle = 'Maintenance Issues (By Equipment)';
                $itemCounts = [];
                
                foreach($reportData as $request) {
                    foreach($request->itemMaintenances as $maintenance) {
                        $name = $maintenance->itemInfo->product_name ?? 'Unknown Equipment';
                        
                        if(!isset($itemCounts[$name])) {
                            $itemCounts[$name] = 0;
                        }
                        $itemCounts[$name] += 1;
                    }
                }
                arsort($itemCounts); // Sort highest to lowest
                $chartLabels = array_keys($itemCounts);
                $chartValues = array_values($itemCounts);
            }
        @endphp

        {{-- ================= RENDER CHART ================= --}}
        @if(!empty($chartLabels) && !empty($chartValues))
            <div class="chart-wrapper">
                <canvas id="reportChart" style="max-height: 300px; width: 100%;"></canvas>
            </div>
        @endif


        {{-- ================= DATA TABLES ================= --}}
        @if(strtolower($report->reportType) === 'usage')
            <div style="overflow-x: auto;">
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="background: #f9fafb; border-bottom: 2px solid #e5e7eb;">
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">No</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Usage ID</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Item ID</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Item Name</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Quantity</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Used By</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Used Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reportData as $record)
                            @foreach($record->itemUsages as $index => $usage)
                                <tr style="border-bottom: 1px solid #f1f5f9;">
                                    <td style="padding: 16px 14px; color: #374151;">{{ $loop->parent->iteration }}.{{ $index + 1 }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">#{{ $record->usageID }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $usage->itemID ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $usage->itemMaintenanceInfo->itemName ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $usage->quantityUsed ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $record->usedByUser->name ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $record->usageDate?->format('Y-m-d') ?? 'N/A' }}</td>
                                </tr>
                            @endforeach
                        @empty
                            <tr>
                                <td colspan="7" style="padding: 50px 20px; text-align: center; color: #6b7280;">
                                    <div style="font-size: 48px; margin-bottom: 10px;">📋</div>
                                    No usage data found for this report period.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

        @elseif(strtolower($report->reportType) === 'maintenance')
            <div style="overflow-x: auto;">
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="background: #f9fafb; border-bottom: 2px solid #e5e7eb;">
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">No</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Request ID</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Item ID</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Equipment Name</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Item Issue</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Submitted By</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Status</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Date Submitted</th>
                            <th style="padding: 16px 14px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280;">Details Maintenance</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reportData as $request)
                            @forelse($request->itemMaintenances as $index => $maintenance)
                                <tr style="border-bottom: 1px solid #f1f5f9;">
                                    <td style="padding: 16px 14px; color: #374151;">{{ $loop->parent->iteration }}.{{ $index + 1 }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">#{{ $request->requestID }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $maintenance->itemInfo->itemID ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $maintenance->itemInfo->product_name ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $maintenance->itemIssue ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $request->submitter->name ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px;">
                                        <span style="padding: 6px 12px; border-radius: 999px; font-size: 12px; font-weight: 600;
                                            @if(strtolower($request->status) === 'completed') background: #ecfdf5; color: #059669;
                                            @elseif(strtolower($request->status) === 'pending') background: #fef3c7; color: #d97706;
                                            @elseif(strtolower($request->status) === 'in-progress') background: #dbeafe; color: #0369a1;
                                            @else background: #fee2e2; color: #dc2626; @endif">
                                            {{ ucfirst($request->status) }}
                                        </span>
                                    </td>
                                    <td style="padding: 16px 14px; color: #374151;">{{ $request->dateSubmitted?->format('Y-m-d H:i') ?? 'N/A' }}</td>
                                    <td style="padding: 16px 14px; color: #374151; max-width: 250px; word-break: break-word;">{{ $maintenance->detailsMaintenance ?? 'N/A' }}</td>
                                </tr>
                            @empty
                                <tr style="border-bottom: 1px solid #f1f5f9;">
                                    <td style="padding: 16px 14px; color: #374151;">{{ $loop->parent->iteration }}</td>
                                    <td colspan="8" style="padding: 16px 14px; color: #6b7280; font-style: italic;">No maintenance items for this request</td>
                                </tr>
                            @endforelse
                        @empty
                            <tr>
                                <td colspan="9" style="padding: 50px 20px; text-align: center; color: #6b7280;">
                                    <div style="font-size: 48px; margin-bottom: 10px;">📋</div>
                                    No maintenance data found for this report period.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

        @else
            <div class="empty-state">
                <div class="empty-state-icon">❓</div>
                <h3>Unknown Report Type</h3>
                <p>This report type is not recognized.</p>
            </div>
        @endif
    </div>
</div>

<div id="printableArea" style="display:none;">
@include('admin.GenerateReport.printable_template_fragment')
</div>

<script>
// ================= INITIALIZE CHART.JS ================= //
document.addEventListener('DOMContentLoaded', function() {
    const ctx = document.getElementById('reportChart');
    if(ctx) {
        new Chart(ctx.getContext('2d'), {
            type: 'pie', // A pie chart to visualize the distribution
            data: {
                labels: @json($chartLabels),
                datasets: [{
                    label: '{{ $chartTitle }}',
                    data: @json($chartValues),
                    backgroundColor: [
                        '#3b82f6', '#10b981', '#f59e0b', '#ef4444', 
                        '#8b5cf6', '#06b6d4', '#f43f5e', '#14b8a6', '#64748b'
                    ],
                    borderWidth: 2,
                    borderColor: '#ffffff',
                    hoverOffset: 6
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'right',
                        labels: { font: { family: 'Inter', size: 13 } }
                    },
                    title: {
                        display: true,
                        text: '{{ $chartTitle }}',
                        font: { family: 'Inter', size: 18, weight: 'bold' },
                        padding: { bottom: 20 }
                    }
                }
            }
        });
    }
});

// ================= PRINT LOGIC ================= //
function printReport() {
    const printable = document.getElementById('printableArea').innerHTML;
    const styles = `
        <style>
            @page { size: A4; margin: 20mm; }
            body { font-family: 'Inter', Arial, sans-serif; color: #111; }
            table { border-collapse: collapse; width: 100%; }
            th { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; font-weight:700; }
            td { padding: 8px; vertical-align: top; }
        </style>
    `;

    const html = '<!doctype html><html><head><meta charset="utf-8"><title>Report #{{ $report->reportID }}</title>' + styles + '</head><body>' + printable + '</body></html>';

    // Open new window
    const w = window.open('', '_blank', 'width=900,height=700');
    if (!w) {
        alert('Please allow popups for this site to print reports.');
        return;
    }

    // Write content to new window
    w.document.open();
    w.document.write(html);
    w.document.close();
    w.focus();

    // Wait for content to load, then print
    setTimeout(() => {
        try { w.print(); } catch (e) { console.error('Print error:', e); }
    }, 300);
}

// Auto-trigger print when ?print=1 is present
document.addEventListener('DOMContentLoaded', function() {
    try {
        const params = new URLSearchParams(window.location.search);
        if (params.get('print') === '1') {
            setTimeout(() => { if (typeof printReport === 'function') printReport(); }, 500);
        }
    } catch (e) { /* ignore */ }
});
</script>
@endsection